[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.90"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
aes-gcm = "0.10"
base64 = "0.22"
data-encoding = "2"
uuid = { version = "1", features = ["v4"] }
urlencoding = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "cookies"] }
tokio = { version = "1", features = ["full"] }
tauri-plugin-stronghold = "2"
tauri-plugin-barcode-scanner = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-biometric = "2"
tauri-plugin-http = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

